// localization.dart

class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(String locale) {
    return AppLocalizations(locale);
  }

  String translate(String key) {
    final translations = _localizedValues[locale] ?? _localizedValues['ja']!;
    return translations[key] ?? key;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'ja': {
      'appTitle': '異獣ペット覚醒計算ツール',
      'availableResources': '使用可能リソース',
      'ownedResources': '所持リソース',
      'core': 'コア',
      'crystal': 'クリスタル',
      'biscuit': 'ビスケット',
      'petSetup': 'ペット編成',
      'mainPet': 'メイン',
      'helperPet': 'ヘルパー',
      'calculate': '計算',
      'optimalSetup': '最適編成',
      'referenceSetup': '参考編成例',
      'awakening': '覚醒',
      'level': 'LV',
      'skillSlots': 'スキル枠',
      'pet': 'ペット',
      'resonanceRate': '共鳴確率',
      'resonanceDamage': '共鳴ダメージ',
      'shield': 'シールド',
      'freeze': '氷結',
      'freezeSkill': '氷結',
      'weakness': '衰弱',
      'poison': '毒',
      'total': '合計',
      'penguin': 'ペンガー',
      'pufferfish': 'フグフグ',
      'chicken': 'チキチキ',
      'capybara': 'カピカピ',
      'petType': 'ペット種類',
      'mainAndHelperPet': 'メインとヘルパーペット',
      'sameType': '同種',
      'differentType': '別種',
      'mainPetAwakeningLevel': 'メインペット覚醒LV',
      'helperPetAwakeningLevel': 'ヘルパーペット覚醒LV',
      'resourceUsageStatus': 'リソース使用状況',
      'usedResources': '使用リソース',
      'remainingResources': '余りリソース',
    },
    'en': {
      'appTitle': 'Beast Pet Awakening Calculator',
      'availableResources': 'Available Resources',
      'ownedResources': 'Owned Resources',
      'core': 'Core',
      'crystal': 'Crystal',
      'biscuit': 'Biscuit',
      'petSetup': 'Pet Setup',
      'mainPet': 'Main',
      'helperPet': 'Helper',
      'calculate': 'Calculate',
      'optimalSetup': 'Optimal Setup',
      'referenceSetup': 'Reference Setup',
      'awakening': 'Awakening',
      'level': 'LV',
      'skillSlots': 'Skill Slots',
      'pet': 'Pet',
      'resonanceRate': 'Resonance Rate',
      'resonanceDamage': 'Resonance Damage',
      'shield': 'Shield',
      'freeze': 'Freeze',
      'freezeSkill': 'Freeze',
      'weakness': 'Weakness',
      'poison': 'Poison',
      'total': 'Total',
      'penguin': 'Penguin',
      'pufferfish': 'Pufferfish',
      'chicken': 'Chicken',
      'capybara': 'Capybara',
      'petType': 'Pet Type',
      'mainAndHelperPet': 'Main and Helper Pets',
      'sameType': 'Same Type',
      'differentType': 'Different Type',
      'mainPetAwakeningLevel': 'Main Pet Awakening LV',
      'helperPetAwakeningLevel': 'Helper Pet Awakening LV',
      'resourceUsageStatus': 'Resource Usage',
      'usedResources': 'Used',
      'remainingResources': 'Remaining',
    },
    'zh': {
      'appTitle': '异兽宠物觉醒计算工具',
      'availableResources': '可用资源',
      'ownedResources': '拥有资源',
      'core': '核心',
      'crystal': '水晶',
      'biscuit': '饼干',
      'petSetup': '宠物配置',
      'mainPet': '主宠',
      'helperPet': '辅助',
      'calculate': '计算',
      'optimalSetup': '最优配置',
      'referenceSetup': '参考配置例',
      'awakening': '觉醒',
      'level': '等级',
      'skillSlots': '技能槽',
      'pet': '宠物',
      'resonanceRate': '共鸣概率',
      'resonanceDamage': '共鸣伤害',
      'shield': '护盾',
      'freeze': '冰冻',
      'freezeSkill': '冰冻',
      'weakness': '虚弱',
      'poison': '中毒',
      'total': '合计',
      'penguin': '企鹅',
      'pufferfish': '河豚',
      'chicken': '小鸡',
      'capybara': '水豚',
      'petType': '宠物种类',
      'mainAndHelperPet': '主宠和辅助宠物',
      'sameType': '同种',
      'differentType': '异种',
      'mainPetAwakeningLevel': '主宠觉醒等级',
      'helperPetAwakeningLevel': '辅助宠物觉醒等级',
      'resourceUsageStatus': '资源使用情况',
      'usedResources': '已使用',
      'remainingResources': '剩余',
    },
    'ko': {
      'appTitle': '이수 펫 각성 계산 도구',
      'availableResources': '사용 가능한 자원',
      'ownedResources': '보유 자원',
      'core': '코어',
      'crystal': '크리스탈',
      'biscuit': '비스킷',
      'petSetup': '펫 구성',
      'mainPet': '메인',
      'helperPet': '헬퍼',
      'calculate': '계산',
      'optimalSetup': '최적 구성',
      'referenceSetup': '참고 구성 예',
      'awakening': '각성',
      'level': '레벨',
      'skillSlots': '스킬 슬롯',
      'pet': '펫',
      'resonanceRate': '공명 확률',
      'resonanceDamage': '공명 데미지',
      'shield': '쉴드',
      'freeze': '빙결',
      'freezeSkill': '빙결',
      'weakness': '쇠약',
      'poison': '독',
      'total': '합계',
      'penguin': '펭귄',
      'pufferfish': '복어',
      'chicken': '닭',
      'capybara': '카피바라',
      'petType': '펫 종류',
      'mainAndHelperPet': '메인 및 헬퍼 펫',
      'sameType': '동종',
      'differentType': '이종',
      'mainPetAwakeningLevel': '메인 펫 각성 레벨',
      'helperPetAwakeningLevel': '헬퍼 펫 각성 레벨',
      'resourceUsageStatus': '자원 사용 현황',
      'usedResources': '사용',
      'remainingResources': '남은',
    },
  };
}
